/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webbrowser;

import java.util.ArrayList;

/**
 *
 * @author Ben_Benign
 */
public class webBrowserForm extends javax.swing.JFrame {
    private ArrayList<BrowserPanel> browserList;
    /**
     * Creates new form webBrowserForm
     */
    public webBrowserForm() {
        initComponents();
        this.browserList = new ArrayList<BrowserPanel>();
        createNewBrowserTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browserTabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        getAllPagesButton = new javax.swing.JButton();
        newTabButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boonyaporn Sangma s4050904@kmitl.ac.th - Java Web Browser (Network Programming Class Assignment#2)");

        statusTextArea.setColumns(20);
        statusTextArea.setRows(5);
        jScrollPane1.setViewportView(statusTextArea);

        getAllPagesButton.setText("GET ALL PAGE");
        getAllPagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllPagesButtonActionPerformed(evt);
            }
        });

        newTabButton.setText("NEW TAB");
        newTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTabButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(browserTabPane))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(784, Short.MAX_VALUE)
                .addComponent(getAllPagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getAllPagesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(newTabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browserTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getAllPagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllPagesButtonActionPerformed
        // TODO add your handling code here:
         for(BrowserPanel browser : this.browserList){
            WebBrowserPane webPane = browser.getWebPane();
            String webAddress = browser.getBrowserToolBar().getAddressTxtField().getText();
            
            webPane.goToWeb(webAddress);
        }
    }//GEN-LAST:event_getAllPagesButtonActionPerformed

    private void newTabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTabButtonActionPerformed
        // TODO add your handling code here:
         createNewBrowserTab();
    }//GEN-LAST:event_newTabButtonActionPerformed

           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(webBrowserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(webBrowserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(webBrowserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(webBrowserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new webBrowserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane browserTabPane;
    private javax.swing.JButton getAllPagesButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newTabButton;
    private javax.swing.JTextArea statusTextArea;
    // End of variables declaration//GEN-END:variables

    private void createNewBrowserTab(){
        String webTitle = "" + (this.browserList.size()+1);
        WebBrowserPane browser = new WebBrowserPane(webTitle, this.statusTextArea);
        BrowserToolBar bar = new BrowserToolBar(browser);
        BrowserPanel newTab = new BrowserPanel(bar, browser);
        this.browserList.add(newTab);
        
        if(this.browserTabPane.getTabCount() == 0){
            this.browserTabPane.add("New Tab", newTab);
        } else {
            this.browserTabPane.add("New Tab " + this.browserTabPane.getTabCount(), newTab);
        }
        this.browserTabPane.setSelectedIndex(this.browserTabPane.getTabCount()-1);
    }
}
